apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadvisor
commonLabels:
  app: cadvisor
resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- daemonset.yaml
- podsecuritypolicy.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- service.yaml
